spring:
   application:
      name: miscrservice-provider-movie-feign
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://yangrui:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
