server:
  port: 8080
spring:
   application:
      name: miscrservice-provider-ribbo

eureka:
  client:
    serviceUrl:
      defaultZone: http://yangrui:123@localhost:8761/eureka
#    healthcheck:
#            enabled: true
  instance:
     prefer-ip-address: true
     instance-id: ${spring.application.name}:${server.port}}
     lease-renewal-interval-in-seconds: 10
     lease-expiration-duration-in-seconds : 60
