security:
  basic:
     enabled: true
  user:
    name: yangrui
    password: 123
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://yangrui:123@localhost:8761/eureka
    healthcheck:
        enabled: true
  server:
    enable-self-preservation: false

    eviction-interval-timer-in-ms: 6000


